#
# Defines environment variables.
#
# Authors:
# c  Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
# if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
#   source "${ZDOTDIR:-$HOME}/.zprofile"
# fi

export SWIFTENV_ROOT="$HOME/.swiftenv"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
